<?php

/**
 * @file
 * Module implementation file.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function shapeshifter_ctools_plugin_directory($module, $plugin) {
  if ($module == 'shapeshifter') {
    return 'plugins/shapeshifter/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function shapeshifter_ctools_plugin_type() {
  $plugins['mapper'] = $plugins['formatter'] = array(
    'classes' => array('class'),
    'process' => 'shapeshifter_plugin_process',
  );
  return $plugins;
}

/**
 * Adds default values to plugin definitions.
 */
function shapeshifter_plugin_process(&$plugin, $info) {
  if ($info['type'] == 'mapper' || $info['type'] == 'formatter') {
    // Set some defaults for the plugin definitions.
  }
}

/**
 * Include CTools plugins and get all mapper plugins.
 *
 * @return array
 *   All plugins for forms.
 */
function shapeshifter_get_mapper_plugins() {
  ctools_include('plugins');
  return ctools_get_plugins('shapeshifter', 'mapper');
}

/**
 * Include CTools plugins and get all mapper plugins.
 *
 * @return array
 *   All plugins for forms.
 */
function shapeshifter_get_formatter_plugins() {
  ctools_include('plugins');
  return ctools_get_plugins('shapeshifter', 'formatter');
}

/**
 * Return the handler object based on the plugin name.
 *
 * @param string $plugin_name
 *   Name of the plugin.
 * @param string $plugin_type
 *   Type of the plugin to get.
 *
 * @return mixed
 *   The handler object.
 */
function shapeshifter_get_plugin_handler($plugin_name, $plugin_type) {
  $plugin = shapeshifter_get_plugin($plugin_name, $plugin_type);
  $class = ctools_plugin_get_class($plugin, 'class');
  return new $class($plugin);
}

/**
 * Returns the mapper handler object based on the entity type and bundle.
 *
 * @param string $entity_type
 *   The type of entity.
 * @param string $bundle
 *   The entity bundle.
 *
 * @return \ShapeshifterMapperBase
 *   The Shapeshifter object.
 */
function shapeshifter_get_mapper_handler($entity_type, $bundle) {
  foreach (ctools_get_plugins('shapeshifter', 'mapper') as $plugin_name => $plugin) {
    if ($plugin['entity_type'] != $entity_type || $plugin['bundle'] != $bundle) {
      continue;
    }
    $class = ctools_plugin_get_class($plugin, 'class');
    return new $class($plugin);
  }
  return NULL;
}

/**
 * Include CTools plugins and get all form plugins.
 *
 * @param string $plugin_name
 *   The name of the plugin to retrieve.
 * @param string $plugin_type
 *   Type of the plugin to get.
 *
 * @return array
 *   The specified plugin.
 */
function shapeshifter_get_plugin($plugin_name, $plugin_type) {
  ctools_include('plugins');
  return ctools_get_plugins('shapeshifter', $plugin_type, $plugin_name);
}
